version: "2.3"
services:
  webapp:
    image: obeliks4j-classla-stanfordnlp:latest
    #runtime: nvidia
    ports:
        - 127.0.0.1:5000:80
    environment:
        - DATA_DIR=/data
        #- NVIDIA_VISIBLE_DEVICES=all
    volumes:
        - <host data dir>:/data
        - <host model dir>:/pipeline/models
